/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikelompokimk;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author adam
 */
public class HalamanDaftar extends javax.swing.JFrame {

    /**
     * Creates new form HalamanDaftar
     */
    public HalamanDaftar() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiobutton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texkinputnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        texttempatlahir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texttanggallahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kewarganegaraancombobox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        agamacombobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        textTelpn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textNik = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lakiradiobutton = new javax.swing.JRadioButton();
        perempuanradiobutton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpanealamat = new javax.swing.JTextPane();
        textprovinsi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textkodepos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textkabkota = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textkecmatan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pendidikancombobox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        textnamsekolah = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jurusan1 = new javax.swing.JComboBox<>();
        jurusan2 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        daftar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        setujucekbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(150, 100));

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 30)); // NOI18N
        jLabel1.setText("Form Pendaftaran Mahasiswa");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1050, 1030));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1005, 1000));

        jLabel2.setBackground(new java.awt.Color(51, 0, 51));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Data diri");

        jLabel3.setText("Nama Lengkap :");

        texkinputnama.setForeground(new java.awt.Color(153, 153, 153));
        texkinputnama.setText("Masukan nama anda");
        texkinputnama.setToolTipText("");
        texkinputnama.setName(""); // NOI18N
        texkinputnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texkinputnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texkinputnamaFocusLost(evt);
            }
        });
        texkinputnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texkinputnamaKeyTyped(evt);
            }
        });

        jLabel4.setText("Tempat Lahir:");

        texttempatlahir.setForeground(new java.awt.Color(153, 153, 153));
        texttempatlahir.setText("Masukan Tempat lahir");
        texttempatlahir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texttempatlahirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texttempatlahirFocusLost(evt);
            }
        });
        texttempatlahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texttempatlahirKeyTyped(evt);
            }
        });

        jLabel5.setText("Tanggal Lahir :");

        texttanggallahir.setForeground(new java.awt.Color(153, 153, 153));
        texttanggallahir.setText("tg/bl/thn");
        texttanggallahir.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        texttanggallahir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texttanggallahirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texttanggallahirFocusLost(evt);
            }
        });
        texttanggallahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texttanggallahirKeyTyped(evt);
            }
        });

        jLabel6.setText("Kewarganegaraan :");

        kewarganegaraancombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih:", "Indonesia", "Malaysia", "Filipina", "Singapura", "Thailand", "Brunei Darussalam", "Vietnam", "Laos", "Kamboja", "Myanmar", "Jepang", "Amerika Seikat", "Saudi Arabia" }));

        jLabel7.setText("Agama:");

        agamacombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Christianity", "Islam", "Hinduism", "Buddhism", "Judaism", "Sikhism", "Taoism", "Zoroastrianism", "Baha'i Faith", "Jainism", "Shinto" }));

        jLabel8.setText("Email :");

        textEmail.setForeground(new java.awt.Color(153, 153, 153));
        textEmail.setText("Example@gmail.com");
        textEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textEmailFocusLost(evt);
            }
        });
        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        textEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEmailKeyTyped(evt);
            }
        });

        textTelpn.setForeground(new java.awt.Color(153, 153, 153));
        textTelpn.setText("08......");
        textTelpn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textTelpnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textTelpnFocusLost(evt);
            }
        });
        textTelpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelpnActionPerformed(evt);
            }
        });
        textTelpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelpnKeyTyped(evt);
            }
        });

        jLabel9.setText("No.Telpon:");

        textNik.setForeground(new java.awt.Color(153, 153, 153));
        textNik.setText("Masukan NIK");
        textNik.setToolTipText("");
        textNik.setName(""); // NOI18N
        textNik.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNikFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNikFocusLost(evt);
            }
        });
        textNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNikKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNikKeyTyped(evt);
            }
        });

        jLabel10.setText("Nomor Identitas (NIK) :");

        jLabel11.setText("Jenis Kelamin:");

        radiobutton.add(lakiradiobutton);
        lakiradiobutton.setText("Laki-laki");

        radiobutton.add(perempuanradiobutton);
        perempuanradiobutton.setText("Perempuan");

        jLabel12.setText("Alamat :");

        textpanealamat.setForeground(new java.awt.Color(153, 153, 153));
        textpanealamat.setText("Ketikan");
        textpanealamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textpanealamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textpanealamatFocusLost(evt);
            }
        });
        textpanealamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textpanealamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textpanealamat);

        textprovinsi.setForeground(new java.awt.Color(153, 153, 153));
        textprovinsi.setText("provinsi");
        textprovinsi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textprovinsi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textprovinsiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textprovinsiFocusLost(evt);
            }
        });
        textprovinsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textprovinsiKeyTyped(evt);
            }
        });

        jLabel13.setText("Provinsi:");

        textkodepos.setForeground(new java.awt.Color(153, 153, 153));
        textkodepos.setText("Kode pos");
        textkodepos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textkodepos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textkodeposFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textkodeposFocusLost(evt);
            }
        });
        textkodepos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textkodeposKeyTyped(evt);
            }
        });

        jLabel14.setText("Kode Pos:");

        textkabkota.setForeground(new java.awt.Color(153, 153, 153));
        textkabkota.setText("kab/kota");
        textkabkota.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textkabkota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textkabkotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textkabkotaFocusLost(evt);
            }
        });
        textkabkota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textkabkotaKeyTyped(evt);
            }
        });

        jLabel15.setText("Kabupaten/Kota:");

        textkecmatan.setForeground(new java.awt.Color(153, 153, 153));
        textkecmatan.setText("kecamatan");
        textkecmatan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textkecmatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textkecmatanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textkecmatanFocusLost(evt);
            }
        });
        textkecmatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textkecmatanKeyTyped(evt);
            }
        });

        jLabel16.setText("Kecamatan:");

        jLabel17.setText("Pendidikan Terakhir:");

        pendidikancombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "SD/MI", "SMP/MT", "SMA/MA", "SMK/MAK/SMAK" }));

        jLabel18.setText("Nama Sekolah:");

        textnamsekolah.setForeground(new java.awt.Color(153, 153, 153));
        textnamsekolah.setText("nama sekolah");
        textnamsekolah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textnamsekolahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textnamsekolahFocusLost(evt);
            }
        });
        textnamsekolah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textnamsekolahKeyTyped(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(51, 0, 51));
        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Data Alamat");

        jLabel20.setBackground(new java.awt.Color(51, 0, 51));
        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Pilihan Program Studi");

        jLabel21.setText("Pilih Program Studi 1:");

        jurusan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jurusan:", "S1 -Teknik Informatika", "S1 -Teknik Kelautan", "S1 -Teknik Perikanan", "S1 -Sains dan Teknologi Kelautan", "S1 -Manajemen Perikanan", "S1 -Oceanografi", "S1 -Meteorologi dan Klimatologi", "S1 -Geofisika" }));

        jurusan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jurusan:", "S1 -Teknik Informatika", "S1 -Teknik Kelautan", "S1 -Teknik Perikanan", "S1 -Sains dan Teknologi Kelautan", "S1 -Manajemen Perikanan", "S1 -Oceanografi", "S1 -Meteorologi dan Klimatologi", "S1 -Geofisika" }));

        jLabel22.setText("Pilih Program Studi 2:");

        daftar.setBackground(new java.awt.Color(0, 51, 255));
        daftar.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        daftar.setForeground(new java.awt.Color(255, 255, 255));
        daftar.setText("Daftar");
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        setujucekbox.setText("Saya telah menyetujui persyaratan");
        setujucekbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setujucekboxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texkinputnama, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(texttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lakiradiobutton)
                                .addGap(51, 51, 51)
                                .addComponent(perempuanradiobutton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(kewarganegaraancombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agamacombobox, 0, 185, Short.MAX_VALUE)
                                    .addComponent(jLabel7))))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNik, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textTelpn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(77, 77, 77))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(pendidikancombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, Short.MAX_VALUE))
                            .addComponent(textnamsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(219, 219, 219)
                                                .addComponent(jLabel15)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(textkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(186, 186, 186)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textkecmatan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textprovinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textkabkota, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jurusan1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setujucekbox))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jurusan2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(416, 416, 416)
                                .addComponent(daftar)
                                .addGap(47, 47, 47)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)))
                        .addGap(52, 52, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texkinputnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendidikancombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textnamsekolah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lakiradiobutton)
                        .addComponent(perempuanradiobutton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kewarganegaraancombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agamacombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textprovinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textkabkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textkecmatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jurusan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jurusan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(setujucekbox)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftar)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(kembali)
                .addGap(62, 62, 62))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1)
                        .addGap(0, 335, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texkinputnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texkinputnamaFocusGained
        // TODO add your handling code here:
        if (texkinputnama.getText().equals("Masukan nama anda")) {
            texkinputnama.setText("");
            texkinputnama.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_texkinputnamaFocusGained

    private void texkinputnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texkinputnamaFocusLost
        // TODO add your handling code here:
        if (texkinputnama.getText().equals("")) {
            texkinputnama.setText("Masukan nama anda");
            texkinputnama.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_texkinputnamaFocusLost

    private void texttempatlahirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texttempatlahirFocusGained
        // TODO add your handling code here:
        if (texttempatlahir.getText().equals("Masukan Tempat lahir")) {
            texttempatlahir.setText("");
            texttempatlahir.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_texttempatlahirFocusGained

    private void texttempatlahirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texttempatlahirFocusLost
        // TODO add your handling code here:
        if (texttempatlahir.getText().equals("")) {
            texttempatlahir.setText("Masukan Tempat lahir");
            texttempatlahir.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_texttempatlahirFocusLost

    private void texttanggallahirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texttanggallahirFocusGained
        // TODO add your handling code here:
        if (texttanggallahir.getText().equals("tg/bl/thn")) {
            texttanggallahir.setText("");
            texttanggallahir.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_texttanggallahirFocusGained

    private void texttanggallahirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texttanggallahirFocusLost
        // TODO add your handling code here:
        if (texttanggallahir.getText().equals("")) {
            texttanggallahir.setText("tg/bl/thn");
            texttanggallahir.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_texttanggallahirFocusLost

    private void textEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailFocusGained
        // TODO add your handling code here:
        if (textEmail.getText().equals("Example@gmail.com")) {
            textEmail.setText("");
            textEmail.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textEmailFocusGained

    private void textEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailFocusLost
        // TODO add your handling code here:
        if (textEmail.getText().equals("")) {
            textEmail.setText("Example@gmail.com");
            textEmail.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textEmailFocusLost

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void textTelpnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTelpnFocusGained
        // TODO add your handling code here:
        if (textTelpn.getText().equals("08......")) {
            textTelpn.setText("");
            textTelpn.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textTelpnFocusGained

    private void textTelpnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTelpnFocusLost
        // TODO add your handling code here:
        if (textTelpn.getText().equals("")) {
            textTelpn.setText("08......");
            textTelpn.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textTelpnFocusLost

    private void textTelpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelpnActionPerformed

    private void textNikFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNikFocusGained
        // TODO add your handling code here:
        if (textNik.getText().equals("Masukan NIK")) {
            textNik.setText("");
            textNik.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textNikFocusGained

    private void textNikFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNikFocusLost
        // TODO add your handling code here:
        if (textNik.getText().equals("")) {
            textNik.setText("Masukan NIK");
            textNik.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textNikFocusLost

    private void textpanealamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textpanealamatFocusGained
        // TODO add your handling code here:
        if (textpanealamat.getText().equals("Ketikan")) {
            textpanealamat.setText("");
            textpanealamat.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textpanealamatFocusGained

    private void textpanealamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textpanealamatFocusLost
        // TODO add your handling code here:
        if (textpanealamat.getText().equals("")) {
            textpanealamat.setText("Ketikan");
            textpanealamat.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textpanealamatFocusLost

    private void textprovinsiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textprovinsiFocusGained
        // TODO add your handling code here:
        if (textprovinsi.getText().equals("provinsi")) {
            textprovinsi.setText("");
            textprovinsi.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textprovinsiFocusGained

    private void textprovinsiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textprovinsiFocusLost
        // TODO add your handling code here:
        if (textprovinsi.getText().equals("")) {
            textprovinsi.setText("provinsi");
            textprovinsi.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textprovinsiFocusLost

    private void textkodeposFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textkodeposFocusGained
        // TODO add your handling code here:
        if (textkodepos.getText().equals("Kode pos")) {
            textkodepos.setText("");
            textkodepos.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textkodeposFocusGained

    private void textkodeposFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textkodeposFocusLost
        // TODO add your handling code here:
        if (textkodepos.getText().equals("")) {
            textkodepos.setText("Kode pos");
            textkodepos.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textkodeposFocusLost

    private void textkabkotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textkabkotaFocusGained
        // TODO add your handling code here:
        if (textkabkota.getText().equals("kab/kota")) {
            textkabkota.setText("");
            textkabkota.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textkabkotaFocusGained

    private void textkabkotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textkabkotaFocusLost
        // TODO add your handling code here:
        if (textkabkota.getText().equals("")) {
            textkabkota.setText("kab/kota");
            textkabkota.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textkabkotaFocusLost

    private void textkecmatanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textkecmatanFocusGained
        // TODO add your handling code here:
        if (textkecmatan.getText().equals("kecamatan")) {
            textkecmatan.setText("");
            textkecmatan.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textkecmatanFocusGained

    private void textkecmatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textkecmatanFocusLost
        // TODO add your handling code here:

        if (textkecmatan.getText().equals("")) {
            textkecmatan.setText("kecamatan");
            textkecmatan.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textkecmatanFocusLost

    private void textnamsekolahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textnamsekolahFocusGained
        // TODO add your handling code here:
        if (textnamsekolah.getText().equals("nama sekolah")) {
            textnamsekolah.setText("");
            textnamsekolah.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_textnamsekolahFocusGained

    private void textnamsekolahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textnamsekolahFocusLost
        // TODO add your handling code here:
        if (textnamsekolah.getText().equals("")) {
            textnamsekolah.setText("nama sekolah");
            textnamsekolah.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textnamsekolahFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        texkinputnama.setText("Masukan nama anda");
        texttempatlahir.setText("Masukan Tempat lahir");
        texttanggallahir.setText("tg/bl/thn");
        lakiradiobutton.setSelected(false);
        perempuanradiobutton.setSelected(false);
        kewarganegaraancombobox.setSelectedIndex(0);
        agamacombobox.setSelectedIndex(0);
        textNik.setText("Masukan NIK");
        textTelpn.setText("08......");
        pendidikancombobox.setSelectedIndex(0);
        textEmail.setText("Example@gmail.com");
        textnamsekolah.setText("nama sekolah");
        textpanealamat.setText("Ketikan");
        textkodepos.setText("Kode pos");
        textprovinsi.setText("provinsi");
        textkabkota.setText("kab/kota");
        textkecmatan.setText("kecamatan");
        jurusan1.setSelectedIndex(0);
        jurusan2.setSelectedIndex(0);
        setujucekbox.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        Halaman_utama utama = new Halaman_utama();
        utama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
        // TODO add your handling code here:
        if (setujucekbox.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "klik centang untuk menyetujui", "error", JOptionPane.ERROR_MESSAGE);
        } else{
            String jeniskelamin="";
            if (lakiradiobutton.isSelected()) {
                jeniskelamin = "Laki-laki";
            } else {
                jeniskelamin = "Perempuan";
            }
//            System.out.println("nama = "+texkinputnama.getText());
//            System.out.println("tempat lahir = "+texttempatlahir.getText());
//            System.out.println("Tanggal lahir = "+ texttanggallahir.getText());
//            System.out.println("Jenis kelamin = "+ jeniskelamin);
//            System.out.println("Kewarganegaraan = "+ kewarganegaraancombobox.getSelectedItem());
//            System.out.println("Agama = "+agamacombobox.getSelectedItem());
//            System.out.println("NIK = "+textNik.getText());
//            System.out.println("Email = "+textEmail.getText());
//            System.out.println("No telpon = "+textTelpn.getText());
//            System.out.println("Pendidikan = "+pendidikancombobox.getSelectedItem());
//            System.out.println("Nama Sekolah = "+textnamsekolah.getText());
//            System.out.println("Kode pos = "+textkodepos.getText());
//            System.out.println("Jurusan ke 1 = "+jurusan1.getSelectedItem());
//            System.out.println("Jurusan ke 2 = "+jurusan2.getSelectedItem());
//            System.out.println("Alamat = "+ textpanealamat.getText());
//            System.out.println("Provinsi = "+textprovinsi.getText());
//            System.out.println("Kecamatan = "+textkecmatan.getText());
//            System.out.println("Kabupaten / kota = "+ textkabkota.getText());
            try {
               
                String sql = "INSERT INTO Tabel_Pendaftaran(Nama_lengkap, Tempat_lahir, Tanggal_lahir, Jenis_kelamin, Kewarganegaraan, Agama, NIK, Email, No_telpon, Pendidikan_Terakhir, Nama_sekolah, Kode_pos, Program_study_1, Program_study_2, Provinsi, Alamat, Kecamatan, kabupaten) VALUES('"
                        + texkinputnama.getText() + "','"
                        + texttempatlahir.getText() + "','"
                        + texttanggallahir.getText() + "','"
                        + jeniskelamin + "','"
                        + kewarganegaraancombobox.getSelectedItem() + "','"
                        + agamacombobox.getSelectedItem() + "','"
                        + textNik.getText() + "','"
                        + textEmail.getText() + "','"
                        + textTelpn.getText() + "','"
                        + pendidikancombobox.getSelectedItem() + "','"
                        + textnamsekolah.getText() + "','"
                        + textkodepos.getText() + "','"
                        + jurusan1.getSelectedItem() + "','"
                        + jurusan2.getSelectedItem() + "','"
                        + textpanealamat.getText() + "','"
                        + textprovinsi.getText() + "','"
                        + textkecmatan.getText() + "','"
                        + textkabkota.getText() + "')";

                Connection conn = (Connection) DBConnection.connectDatabase();
                PreparedStatement pst =conn.prepareStatement(sql);
                              
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(HalamanDaftar.class.getName()).log(Level.SEVERE, null, ex);
            }
            Halaman_utama utama = new Halaman_utama();
            utama.setVisible(true);
            this.dispose();
      
        }
    }//GEN-LAST:event_daftarActionPerformed

    private void texttanggallahirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texttanggallahirKeyTyped
        // TODO add your handling code here:
        char keychar = evt.getKeyChar();
        if (texttanggallahir.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
         if (Character.isLetter(keychar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Harus angka");

        }
    }//GEN-LAST:event_texttanggallahirKeyTyped

    private void textNikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNikKeyTyped
        // TODO add your handling code here:
        char keychar = evt.getKeyChar();
        if (textNik.getText().length() > 16) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }

        if (Character.isLetter(keychar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Harus angka");

        }

    }//GEN-LAST:event_textNikKeyTyped

    private void textTelpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelpnKeyTyped
        // TODO add your handling code here:
        char keychar = evt.getKeyChar();
        if (textTelpn.getText().length() >= 15) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");

        }
        if (Character.isLetter(keychar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Harus angka");

        }
    }//GEN-LAST:event_textTelpnKeyTyped

    private void textNikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNikKeyReleased
        // TODO add your handling code here:
        if (textNik.getText().equals("")) {
            textNik.setText("Masukan NIK");
            textNik.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textNikKeyReleased

    private void textEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEmailKeyTyped
        // TODO add your handling code here:
        if (textEmail.getText().length() >= 30) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_textEmailKeyTyped

    private void texkinputnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texkinputnamaKeyTyped
        // TODO add your handling code here:
        if (texkinputnama.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");

        }
    }//GEN-LAST:event_texkinputnamaKeyTyped

    private void textnamsekolahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnamsekolahKeyTyped
        // TODO add your handling code here:
        if (textnamsekolah.getText().length() >= 30) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");

        }
    }//GEN-LAST:event_textnamsekolahKeyTyped

    private void textpanealamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textpanealamatKeyTyped
        // TODO add your handling code here:
        if (textpanealamat.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_textpanealamatKeyTyped

    private void textkodeposKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textkodeposKeyTyped
        // TODO add your handling code here:
        if (textkodepos.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }

        char keychar = evt.getKeyChar();
        if (Character.isLetter(keychar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Harus angka");

        }
    }//GEN-LAST:event_textkodeposKeyTyped

    private void textprovinsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textprovinsiKeyTyped
        // TODO add your handling code here:
        if (textprovinsi.getText().length() >= 20) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_textprovinsiKeyTyped

    private void textkabkotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textkabkotaKeyTyped
        // TODO add your handling code here:
        if (textkabkota.getText().length() >= 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_textkabkotaKeyTyped

    private void textkecmatanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textkecmatanKeyTyped
        // TODO add your handling code here:
        if (textkecmatan.getText().length() >= 20) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_textkecmatanKeyTyped

    private void texttempatlahirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texttempatlahirKeyTyped
        // TODO add your handling code here:
        if (texttempatlahir.getText().length() >= 20) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Terlalu panjang");
        }
    }//GEN-LAST:event_texttempatlahirKeyTyped

    private void setujucekboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setujucekboxItemStateChanged
        // TODO add your handling code here:
        if (evt.getSource() == setujucekbox) {
            if (texkinputnama.getText().equals("Masukan nama anda")) {
                JOptionPane.showMessageDialog(null, "Nama belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (texttempatlahir.getText().equals("Masukan Tempat lahir")) {
                JOptionPane.showMessageDialog(null, "Tempal lahir belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (textNik.getText().length() < 16) {
                JOptionPane.showMessageDialog(null, "Nik kurang dari 16 digit", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (textTelpn.getText().equals("08......")) {
                JOptionPane.showMessageDialog(null, "No Telpon belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (pendidikancombobox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Pendidikan belum di pilih", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (textEmail.getText().equals("Example@gmail.com")) {
                JOptionPane.showMessageDialog(null, "Email belum di pilih", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (textnamsekolah.getText().equals("nama sekolah")) {
                JOptionPane.showMessageDialog(null, "Nama sekolah belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (texttanggallahir.getText().length() < 10) {
                JOptionPane.showMessageDialog(null, "tanggal kurang dari 10 digit (dd/yy/YYyy)", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (!lakiradiobutton.isSelected() && !perempuanradiobutton.isSelected()) {
                JOptionPane.showMessageDialog(null, "Jenis kelamin belum dipilih", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (kewarganegaraancombobox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Kewarganegaraan belum dipilih", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if (agamacombobox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Agama belum dipilih", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(textpanealamat.getText().equals("Ketikan")){
                JOptionPane.showMessageDialog(null, "Alamat belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(textkodepos.getText().equals("Kode pos")){
                JOptionPane.showMessageDialog(null, "Kode pos belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(textprovinsi.getText().equals("provinsi")){
                JOptionPane.showMessageDialog(null, "Provinsi belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(textkabkota.getText().equals("kab/kota")){
                JOptionPane.showMessageDialog(null, "Kabupaten/Kota belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(textkecmatan.getText().equals("kecamatan")){
                JOptionPane.showMessageDialog(null, "Kecamatan belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(jurusan1.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Jurusan 1 belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            }
            if(jurusan2.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Jurusan 2 belum di isi", "error", JOptionPane.ERROR_MESSAGE);
                setujucekbox.setSelected(false);
            } 

        }

    }//GEN-LAST:event_setujucekboxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanDaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agamacombobox;
    private javax.swing.JButton daftar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> jurusan1;
    private javax.swing.JComboBox<String> jurusan2;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> kewarganegaraancombobox;
    private javax.swing.JRadioButton lakiradiobutton;
    private javax.swing.JComboBox<String> pendidikancombobox;
    private javax.swing.JRadioButton perempuanradiobutton;
    private javax.swing.ButtonGroup radiobutton;
    private javax.swing.JCheckBox setujucekbox;
    private javax.swing.JTextField texkinputnama;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNik;
    private javax.swing.JTextField textTelpn;
    private javax.swing.JTextField textkabkota;
    private javax.swing.JTextField textkecmatan;
    private javax.swing.JTextField textkodepos;
    private javax.swing.JTextField textnamsekolah;
    private javax.swing.JTextPane textpanealamat;
    private javax.swing.JTextField textprovinsi;
    private javax.swing.JTextField texttanggallahir;
    private javax.swing.JTextField texttempatlahir;
    // End of variables declaration//GEN-END:variables
}
